name: Dynamic Update Docs

on:
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-root:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Determine today's date and corresponding directory
      - name: Determine Today's Directory
        run: |
          TODAY=$(date -u +"%Y-%m-%d")
          echo "dir=dynamic-content-2025/$TODAY" >> $GITHUB_ENV
      # Step 3: Debug directory structure (Optional, for troubleshooting)
      # - name: Debug Directory Structure
      #   run: |
      #     echo "Current directory:"
      #     pwd
      #     echo "Contents of repository:"
      #     ls -R

      # Step 4: Verify that the source directory exists
      - name: Verify Source Directory
        run: |
          if [ ! -d "${{ env.dir }}" ]; then
            echo "Error: Source directory ${{ env.dir }} does not exist!"
            exit 1
          else
            echo "Source directory ${{ env.dir }} exists. Proceeding..."
          fi
      # Step 5: Prepare the public directory
      - name: Prepare Public Directory
        run: |
          mkdir -p docs  # Create the directory if it doesn't exist
          rm -rf docs/*  # Remove existing content
      # Step 6: Copy files from the selected directory to public
      - name: Copy Files to docs Directory
        run: |
          echo "Copying files from ${{ env.dir }} to docs/"
          cp -r ${{ env.dir }}/* docs/
      # Step 7: Commit and Push Changes
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/*
          git commit -m "Update docs directory with content from ${{ env.dir }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}