name: Update Root Directory

on:
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-root:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Determine Today's Directory
        run: |
          TODAY=$(date -u +"%Y-%m-%d")
          echo "dir=dynamic-content-2025/$TODAY" >> $GITHUB_ENV

      - name: Debug Directory Structure
        run: |
          echo "Current directory:"
          pwd
          echo "Contents of repository:"
          ls -R

      - name: Verify Source Directory
        run: |
          if [ ! -d "${{ env.dir }}" ]; then
            echo "Error: Source directory ${{ env.dir }} does not exist!"
            exit 1
          else
            echo "Source directory ${{ env.dir }} exists. Proceeding..."
          fi

      - name: Prepare Public Directory
        run: |
          mkdir -p public  # Create the directory if it doesn't exist
          rm -rf public/*  # Remove existing content

      - name: Copy Files to Public Directory
        run: |
          echo "Copying files from ${{ env.dir }} to public/"
          cp -r ${{ env.dir }}/* public/

      - name: Commit and Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  # Replace with your branch name
          force: true