name: Update Root Directory

on:
  schedule:
    # Run daily at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-root:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Determine today's date and corresponding directory
      - name: Determine Today's Directory
        run: |
          python3 <<EOF
import datetime
today = datetime.datetime.utcnow().date()
folder_name = today.strftime('%Y-%m-%d')
with open("${GITHUB_ENV}", "a") as env_file:
    env_file.write(f"dir=dynamic-content-2025/{folder_name}\n")
EOF

      # Step 3: Copy content to the public (root) directory
      - name: Update Root Directory
        run: |
          echo "Selected source directory: ${{ env.dir }}"
          rm -rf public/*  # Clear existing root content
          cp -r ${{ env.dir }}/* public/

      # Step 4: Commit and push changes
      - name: Commit and Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  # Replace with your Cloudflare Pages branch
          force: true